// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvkdiqdvkshjrcbvrame.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52a2RpcWR2a3NoanJjYnZyYW1lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5NTM4NjYsImV4cCI6MjA1ODUyOTg2Nn0.jOIixOcVLOnCwunuutHnxIj3MT1ox7Cz-FfSczJZ_YA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);